# Generated by Django 3.2.5 on 2021-08-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210725_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Price',
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
